name: Build and Publish

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/heads/') && endsWith(github.ref, '-latest')  # Ensure it only runs if the PR is merged
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you need
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Adjust according to your build script

    - name: Determine Tag
      id: determine-tag
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
        TAG_NAME="ui5-${BRANCH_NAME//./-}"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use the npm token from secrets
      run: npm publish --tag ${{ env.TAG_NAME }}

    - name: Deprecate previous version
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use the npm token from secrets
      run: |
        # Get the current version
        CURRENT_VERSION=$(npm pkg get version | tr -d '"')
        
        # Extract major, minor, and patch numbers
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
        
        # Calculate the previous patch version
        PREVIOUS_PATCH=$((PATCH-1))
        PREVIOUS_VERSION="${MAJOR}.${MINOR}.${PREVIOUS_PATCH}"
        
        # Deprecate the previous version
        npm deprecate "ui5-antares@${PREVIOUS_VERSION}" "This version has some bugs and missing features. Please install the latest version with the following command: npm install --save-exact ui5-antares@${TAG_NAME}"      